version: "3.7"
services:

  database_restaurant:
    image: postgres
    container_name: database_restaurant
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user123
      - POSTGRES_DB=database_restaurant
    volumes:
      - pgdata:/data/postgres


    

  app:
    build: .
    container_name: restaurant_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_restaurant
    depends_on:
      - database_restaurant


volumes:
  pgdata:
    driver: local